package mustafaozhan.github.com.backendccc.tools

/**
 * Created by Mustafa Ozhan on 2018-07-16.
 */
@Suppress("LargeClass")
enum class Currencies(value: String) {
    AE("AED"),
    AF("AFN"),
    AL("ALL"),
    AM("AMD"),
    AN("ANG"),
    AO("AOA"),
    AR("ARS"),
    AU("AUD"),
    AZ("AZN"),
    BA("BAM"),
    BB("BBD"),
    BD("BDT"),
    BG("BGN"),
    BH("BHD"),
    BI("BIF"),
    BM("BMD"),
    BN("BND"),
    BO("BOB"),
    BR("BRL"),
    BS("BSD"),
    BW("BWP"),
    BY("BYR"),
    BZ("BZD"),
    CA("CAD"),
    CD("CDF"),
    CH("CHF"),
    CL("CLP"),
    CN("CNY"),
    CO("COP"),
    CR("CRC"),
    CU("CUP"),
    CV("CVE"),
    CZ("CZK"),
    DJ("DJF"),
    DK("DKK"),
    DO("DOP"),
    DZ("DZD"),
    EG("EGP"),
    ET("ETB"),
    EU("EUR"),
    FJ("FJD"),
    FK("FKP"),
    GB("GBP"),
    GE("GEL"),
    GG("GGP"),
    GH("GHS"),
    GI("GIP"),
    GM("GMD"),
    GN("GNF"),
    GT("GTQ"),
    GY("GYD"),
    HK("HKD"),
    HN("HNL"),
    HR("HRK"),
    HT("HTG"),
    HU("HUF"),
    ID("IDR"),
    IL("ILS"),
    IN("INR"),
    IQ("IQD"),
    IR("IRR"),
    IS("ISK"),
    JM("JMD"),
    JO("JOD"),
    JP("JPY"),
    KE("KES"),
    KG("KGS"),
    KH("KHR"),
    KM("KMF"),
    KP("KPW"),
    KR("KRW"),
    KW("KWD"),
    KY("KYD"),
    KZ("KZT"),
    LA("LAK"),
    LB("LBP"),
    LK("LKR"),
    LR("LRD"),
    LS("LSL"),
    LT("LTL"),
    LV("LVL"),
    LY("LYD"),
    MA("MAD"),
    MD("MDL"),
    MG("MGA"),
    MK("MKD"),
    MM("MMK"),
    MN("MNT"),
    MO("MOP"),
    MR("MRO"),
    MU("MUR"),
    MV("MVR"),
    MW("MWK"),
    MX("MXN"),
    MY("MYR"),
    MZ("MZN"),
    NA("NAD"),
    NG("NGN"),
    NI("NIO"),
    NO("NOK"),
    NP("NPR"),
    NZ("NZD"),
    OM("OMR"),
    PA("PAB"),
    PE("PEN"),
    PG("PGK"),
    PH("PHP"),
    PK("PKR"),
    PL("PLN"),
    PY("PYG"),
    QA("QAR"),
    RO("RON"),
    RS("RSD"),
    RU("RUB"),
    RW("RWF"),
    SA("SAR"),
    SB("SBD"),
    SC("SCR"),
    SD("SDG"),
    SE("SEK"),
    SG("SGD"),
    SL("SLL"),
    SO("SOS"),
    SR("SRD"),
    ST("STD"),
    SV("SVC"),
    SY("SYP"),
    SZ("SZL"),
    TH("THB"),
    TJ("TJS"),
    TM("TMT"),
    TN("TND"),
    TO("TOP"),
    TR("TRY"),
    TT("TTD"),
    TW("TWD"),
    TZ("TZS"),
    UA("UAH"),
    UG("UGX"),
    US("USD"),
    UY("UYU"),
    UZ("UZS"),
    VE("VEF"),
    VN("VND"),
    VU("VUV"),
    CM("XAF"),
    AI("XCD"),
    BJ("XOF"),
    PF("XPF"),
    YE("YER"),
    ZA("ZAR"),
    ZM("ZMK"),
//    ZMW(""), REMOVED
//    ZWL("") REMOVED
//    AWG(""), REMOVED
//    BTC(""), REMOVED
//    BTN(""), REMOVED
//    BYN(""), REMOVED
//    CLF(""), REMOVED
//    CUC(""), REMOVED
//    ERN(""), REMOVED
//    IMP(""), REMOVED
//    JEP(""), REMOVED
//    SHP(""), REMOVED
//    WST(""), REMOVED
//    XAG(""), REMOVED
//    XAU(""), REMOVED
//    XDR(""), REMOVED
}